config:
    QUEUE:
        BROKER_URI: rediss://:mvduJdz5Q1m9MClZzgCWDgqnxIGRpIEF@SG-ribbon-jingle-7313-56758.servers.mongodirector.com:6379
        BACKEND_URI: rediss://:mvduJdz5Q1m9MClZzgCWDgqnxIGRpIEF@SG-ribbon-jingle-7313-56758.servers.mongodirector.com:6379
    POSTGRES:
        URI: postgresql://tappsvd:sa2g5XhpVMqN@ep-red-wood-039855.us-east-2.aws.neon.tech/featurestore
    AZURE:
        CONNECTION_STRING: DefaultEndpointsProtocol=https;AccountName=featurestores;AccountKey=4O2otyNo3Gd5oPgkSrjaI0CfFQYqGxYdq0Ejs7cyo8PTHTVOFUpIELR4MIUhCqTUSQfrf4t8zO89+AStstPqUw==;EndpointSuffix=core.windows.net
    SECRET_KEY: C0mpl1caT3D
    SEGMENT_KEY: 2FoE4FP9AA6dUoJWPrEmuoIIMNvDHwKt
    JWT:
        SECRET: VeD4N5HDW1V3D1
        SALT: 12
    SEGMENT:
        KEY: 2FoE4FP9AA6dUoJWPrEmuoIIMNvDHwKt
    LOCAL_FILE_PATH: files
    MONGO:
        MONGO_URI: mongodb+srv://vedanshcluster:vedanshcluster@vedanshmongocluster.zqkvkn4.mongodb.net/platformv2?retryWrites=true&w=majority
        MONGO_DBNAME: platformv2
    EMAIL:
        USERNAME: testcelery@gmail.com
        PASSWORD: 6F050EAE1D496EAFBCA6C339DFD6DFBF28BE
        SERVER: smtp.elasticemail.com
        PORT: 2525
        API_KEY: 2FB260CBFA07F8A095B56C9AA1E5E78D9145D15C1002D36FB2FA81C1D4F760B08EDABA47B833E925E7F9C5376F338747